---
title: "Kaede_dataset_preprocessing"
author: "Dillon Corvino"
date: "01/02/2024"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}

#Dataset came from communication with David R. Withers, Isaac Dean and Colin Y. C. Lee
# Lee provided dataset used in Dean, Lee et al., 2024 Nature Communications manuscript


```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)


# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# pipeline variables
long.compute <- TRUE
do.plot <- TRUE

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())



# load packages
library(Seurat)
library(SeuratData)
library(dplyr)

```



## Loading and formatting dataset {.tabset}

### convert h5ad object to h5seurat object
```{r convert_dataset}

if(long.compute){
  
  # issue converting h5ad object to h5seurat object using seurat functions
  # therefore use alternative approach using zellkonverter
  #BiocManager::install("zellkonverter")
  
  library("zellkonverter")
  
  ad <- readH5AD("data/processed_NK_concat.h5ad")
  
  kaede.seurat <- as.Seurat(ad, counts = "X", data = NULL)
  
  
  
  #SeuratDisk
  #H5ADToH5Seurat(source, dest, assay = "RNA", overwrite = FALSE, verbose = TRUE)

  # save object as seurat object
  SaveH5Seurat(kaede.seurat, "data/kaede.h5seurat", overwrite = TRUE)
  
}


```

### load dataset
```{r load_dataset}

  # load dataset
  kaede.seurat <- LoadH5Seurat("data/kaede.h5seurat")
  
  kaede.seurat # 16,665 genes across 12,843 cells
  
 
```
 
### Broad visualisation
```{r vis_dataset}

  
output.dir <- "results/data_overview/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}

head(kaede.seurat@meta.data) 



vars.plot <- c("colour", "sort_group", "batch", "time", "celltype_cluster_paper")

for(i in seq_along(vars.plot)){
  
  print(scCustomize::DimPlot_scCustom(kaede.seurat, 
                                      reduction = "X_umap", 
                                      group.by = vars.plot[i], 
                                      pt.size = 1,
                                      label = TRUE,
                                      figure_plot = TRUE)
  )
  
  
  dev.copy(pdf, paste0(output.dir, "UMAP_kaede_grouped_by_", vars.plot[i], ".pdf"))
  dev.off()
  
}

goi <- grep("Gzm.*", rownames(kaede.seurat), value = T)
goi <- c(goi, "Nkg7", "Itga1", "Itga2", "Dgat1", "Dgat2")



goi <- c("Itga1", "Cd160", "Cd3e", "Eomes", "Tbx21")

scCustomize::Stacked_VlnPlot(kaede.seurat, 
                             features = goi,
                             pt.size = 0,
                             group.by = "time")

dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_grouped_by_colour.pdf"))
dev.off()




```
 

 
## Imputation {.tabset}

### Imputate gene expression
```{r imputation}

if(long.compute){
  
  output.dir <- "saves/"
  if(!dir.exists(output.dir)){
    dir.create(output.dir, 
               recursive = T)}
  
  
  # check that genes of interest are in variable genes list 
  kaede.seurat # 16,665 genes across 12,843 cells
  
  DefaultAssay(kaede.seurat) <- "originalexp"
  
  
  kaede.seurat <- FindVariableFeatures(kaede.seurat)
  

  kaede.seurat <- SeuratWrappers::RunALRA(kaede.seurat)
  
  # The matrix went from 14.71% nonzero to 48.12% nonzero
  
  # Export dataset for easy import
  SeuratDisk::SaveH5Seurat(kaede.seurat, "saves/kaede_imputed.h5Seurat", overwrite = TRUE)
  
  DefaultAssay(kaede.seurat) <- "originalexp"
  
}


```

 
  
### DEG analysis
```{r remedy001}

# clean dataset, keep only 48 hour timepoint as this is by far the timepoint with majority of the cells both red and green 

table(kaede.seurat@meta.data$celltype_cluster_paper, kaede.seurat@meta.data$time)


##############################
# keep only 48 hour timepoint
##############################
Idents(kaede.seurat) <- kaede.seurat@meta.data$time
unique(Idents(kaede.seurat))


kaede.seurat.NK <- subset(kaede.seurat, idents = c("Green_48h", "Red_48h"))


##############################
# remove ILC1 and NKT populations 
##############################
Idents(kaede.seurat.NK) <- kaede.seurat.NK@meta.data$celltype_cluster_paper
unique(Idents(kaede.seurat.NK))


kaede.seurat.NK <- subset(kaede.seurat.NK, idents = c("ILC", "NKT"), invert = TRUE)



Idents(kaede.seurat.NK) <- kaede.seurat.NK@meta.data$time
unique(Idents(kaede.seurat.NK))


early.markers <- FindMarkers(kaede.seurat.NK, 
                             ident.1 = "Green_48h", 
                             ident.2 = "Red_48h",
                             min.pct = 0.1)

goi <- early.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::top_n(50, avg_log2FC) %>%
  rownames()

early.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC))
goi


scCustomize::Stacked_VlnPlot(kaede.seurat.NK, 
                             features = goi,
                             pt.size = 0,
                             group.by = "time")




# gene signature 
cd160.sig <- read.csv("data/CD160_DEG_QLF_S.PosvsNeg.csv")

pos.sig <- cd160.sig %>%
  dplyr::filter(FDR < 0.05) %>%
  dplyr::top_n(50, logFC) %>%
  dplyr::arrange(desc(logFC)) %>%
  dplyr::pull(genes)

pos.sig



kaede.seurat.NK <- AddModuleScore(kaede.seurat.NK,
                             features = list(cd160sig = pos.sig), 
                             name = "CD160_sig")


head(kaede.seurat@meta.data)
VlnPlot_scCustom(kaede.seurat.NK, 
                 features = "CD160_sig1", 
                 group.by = "celltype_cluster_paper")


VlnPlot_scCustom(kaede.seurat.NK, 
                 features = "CD160_sig1", 
                 group.by = "time")




VlnPlot_scCustom(kaede.seurat.NK, 
                 features = "Acat2", 
                 group.by = "time")


RidgePlot(kaede.seurat.NK, 
                 features = "CD160_sig1", 
                 group.by = "time")


# IFN-signalling signature 
kaede.seurat.NK




```
 
 
 
### DGAT expression
```{r DGAT_expression}


goi <- c("Nkg7", "Itga1", "Itga2", "Dgat1", "Dgat2")

scCustomize::Stacked_VlnPlot(kaede.seurat, 
                             features = goi,
                             pt.size = 0,
                             group.by = "time")

  dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_grouped_by_colour_dgat.pdf"))
  dev.off()

  
  Idents(kaede.seurat) <- kaede.seurat@meta.data$celltype_cluster_paper
  temp.seurat <- subset(kaede.seurat, idents = c("NK_1", "NK_2", "NK_5"))
  scCustomize::Stacked_VlnPlot(temp.seurat, 
                               features = goi,
                               pt.size = 0.1,
                               group.by = "celltype_cluster_paper")
  
  dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_select_NK_groups_dgat.pdf"))
  dev.off()
  
  
  
  
  
```







