---
title: "Kaede_DGAT_analysis_proteomics_project"
author: "Dillon Corvino"
date: "01/02/2024"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}

#Dataset came from communication with David R. Withers, Isaac Dean and Colin Y. C. Lee
# Lee provided dataset used in Dean, Lee et al., 2024 Nature Communications manuscript


```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)


# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# pipeline variables
long.compute <- TRUE
do.plot <- TRUE

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())



# load packages
library(Seurat)
library(SeuratData)
library(dplyr)

```



## Loading and formatting dataset {.tabset}

### load dataset
```{r load_dataset}

# load dataset
kaede.seurat <- LoadH5Seurat("saves/kaede_imputed.h5Seurat")

kaede.seurat # 16,665 genes across 12,843 cells

DefaultAssay(kaede.seurat) <- "originalexp"
```

### Clean and filter dataset for just NK cells at 48hours
```{r filter_dataset}

# clean dataset, keep only 48 hour timepoint as this is by far the timepoint with majority of the cells both red and green 

table(kaede.seurat@meta.data$celltype_cluster_paper, kaede.seurat@meta.data$time)


##############################
# keep only 48 hour timepoint
##############################
Idents(kaede.seurat) <- kaede.seurat@meta.data$time
unique(Idents(kaede.seurat))


kaede.seurat.NK <- subset(kaede.seurat, idents = c("Green_48h", "Red_48h"))


##############################
# remove ILC1 and NKT populations 
##############################
Idents(kaede.seurat.NK) <- kaede.seurat.NK@meta.data$celltype_cluster_paper
unique(Idents(kaede.seurat.NK))


kaede.seurat.NK <- subset(kaede.seurat.NK, idents = c("ILC", "NKT"), invert = TRUE)

# clean environment
rm(kaede.seurat)
gc()
```


### DGAT expression
```{r DGAT_expression}


output.dir <- paste0("results/DGAT/")

if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)
  
}

scCustomize::VlnPlot_scCustom(kaede.seurat.NK, 
                              features = "Dgat1",
                              pt.size = 0.1,
                              group.by = "time")

dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_NK_only_Dgat1.pdf"))
dev.off()

scCustomize::VlnPlot_scCustom(kaede.seurat.NK, 
                              features = "Dgat2",
                              pt.size = 0.1,
                              group.by = "time")

dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_NK_only_Dgat2.pdf"))
dev.off()





# goi <- c("Nkg7", "Itga1", "Itga2", "Dgat1", "Dgat2")
# 
# scCustomize::Stacked_VlnPlot(kaede.seurat.NK, 
#                              features = goi,
#                              pt.size = 0,
#                              group.by = "time")
# 
# dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_grouped_by_colour_dgat.pdf"))
# dev.off()
# 
# 
# Idents(kaede.seurat) <- kaede.seurat@meta.data$celltype_cluster_paper
# temp.seurat <- subset(kaede.seurat, idents = c("NK_1", "NK_2", "NK_5"))
# scCustomize::Stacked_VlnPlot(temp.seurat, 
#                              features = goi,
#                              pt.size = 0.1,
#                              group.by = "celltype_cluster_paper")
# 
# dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_select_NK_groups_dgat.pdf"))
# dev.off()





```


### Genes of interest - Collagen and Mboat proteins
```{r genes_of_interest}

# Load necessary libraries
library(Seurat)
library(ggplot2)
library(stringr)

# Define input and output paths
input.path  <- "data/susanna_gene_lists/"
output.dir  <- "results/DGAT_project/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)
  
}
# Read gene lists into named list
gene.list.files <- list.files(input.path, pattern = "\\.txt$", full.names = TRUE)

gene.sets <- lapply(gene.list.files, function(f){
  df <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  return(as.character(df[[1]]))  # grab first column regardless of name
})

names(gene.sets) <- basename(gene.list.files) |>
  str_replace_all(" ", "_") |>
  str_remove("\\.txt$")

# Set default assay
DefaultAssay(kaede.seurat.NK) <- "originalexp"

# Compute pseudobulk once
pseudo.by.cluster.time <- AggregateExpression(
  kaede.seurat.NK,
  assays       = "originalexp",
  return.seurat = TRUE,
  group.by     = c("celltype_cluster_paper", "time")
)

pseudo.by.time <- AggregateExpression(
  kaede.seurat.NK,
  assays       = "originalexp",
  return.seurat = TRUE,
  group.by     = "time"
)


gene.sets <- lapply(gene.sets, stringr::str_to_title)

# Generate heatmaps
for(gene.set.name in names(gene.sets)){
  
  genes <- gene.sets[[gene.set.name]]
  
  p1 <- DoHeatmap(
    pseudo.by.cluster.time,
    features    = genes,
    draw.lines  = FALSE,
    raster      = FALSE
  ) + scale_fill_gradient2(low = "blue", mid = "white", high = "red") +
    ggtitle(paste("Pseudobulk by cluster/time:", gene.set.name))
  
  ggsave(
    filename = paste0(output.dir, "Heatmap_cluster_time_", gene.set.name, ".pdf"),
    plot     = p1, width = 8, height = 10
  )
  
  p2 <- DoHeatmap(
    pseudo.by.time,
    features    = genes,
    draw.lines  = FALSE,
    raster      = FALSE
  ) + scale_fill_gradient2(low = "blue", mid = "white", high = "red") +
    ggtitle(paste("Pseudobulk by time:", gene.set.name))
  
  ggsave(
    filename = paste0(output.dir, "Heatmap_time_", gene.set.name, ".pdf"),
    plot     = p2, width = 8, height = 10
  )
}


















```



### Metabolic genes
```{r metabolic_genes_overview}

# create output dir
output.dir <- paste0("results/metabolic_genes/")

if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)
  
}


# list of human metabolic genes of interest provided by susanna to investigate
metabolic.genes <- readxl::read_excel("data/List of metabolic molecules to interrogate in RNA-seq data.xlsx")
metabolic.genes <- metabolic.genes$`Gene name`

# convert to mouse genes
metabolic.genes.mouse <- usefulfunctions::convert.human.to.mouse(metabolic.genes, use.jax = TRUE)
length(metabolic.genes.mouse) # 49
length(metabolic.genes) # 51


for(i in seq_along(metabolic.genes.mouse)){
  
  if(metabolic.genes.mouse[i] %in% rownames(kaede.seurat.NK)){
    print(
      scCustomize::VlnPlot_scCustom(kaede.seurat.NK, 
                                    features = metabolic.genes.mouse[i],
                                    pt.size = 0.1,
                                    group.by = "time")
    )
    dev.copy(pdf, paste0(output.dir, "VlnPlot_", metabolic.genes.mouse[i], ".pdf"))
    dev.off()
    
  }
}




DefaultAssay(kaede.seurat.NK) <- "originalexp"

# create pseudobulk for visualisation
pseudo.NK <- AggregateExpression(kaede.seurat.NK, 
                                 assays = "originalexp",
                                 return.seurat = TRUE,
                                 group.by = c("celltype_cluster_paper", "time"))


DoHeatmap(pseudo.NK, 
          features = metabolic.genes.mouse, 
          draw.lines = FALSE, 
          raster = FALSE)

dev.copy(pdf, paste0(output.dir, "Heatmap_pseudobulk_cluster_time_metabolic_genes.pdf"))
dev.off()





pseudo.NK <- AggregateExpression(kaede.seurat.NK, 
                                 assays = "originalexp",
                                 return.seurat = TRUE,
                                 group.by = c("time"))


DoHeatmap(pseudo.NK, 
          features = metabolic.genes.mouse, 
          draw.lines = FALSE, 
          raster = FALSE)

dev.copy(pdf, paste0(output.dir, "Heatmap_pseudobulk_time_metabolic_genes.pdf"))
dev.off()

```



# below is a working zone
### Cytotoxic molecule expression
```{r cytotoxic_molecules}


output.dir <- paste0("results/cytotoxic_molecules/")

if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)
  
}


cytotoxicity.markers <- c("Gzma", "Gzmb", "Gzmh", "Gzmk", "Gzmm", "Gnly", "Prf1", "Nkg7")

scCustomize::Stacked_VlnPlot(kaede.seurat.NK, 
                              features = cytotoxicity.markers,
                              pt.size = 0,
                              group.by = "time")

dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_NK_only_cytotoxic_molecules.pdf"))
dev.off()





goi <- early.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  rownames()

logic.vec <- cytotoxicity.markers %in% goi
cytotoxicity.markers[logic.vec]

early.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
tibble::rownames_to_column() %>%
  dplyr::filter(rowname %in% cytotoxicity.markers)



Idents(temp.seurat) <- temp.seurat@meta.data$time
average.seurat <- AverageExpression(temp.seurat, features = cytotoxicity.markers, return.seurat = T)

DoHeatmap(average.seurat, cytotoxicity.markers, draw.lines = F)




#dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_NK_only_cytotoxic.pdf"))
#dev.off()

scCustomize::VlnPlot_scCustom(kaede.seurat.NK, 
                              features = "Dgat2",
                              pt.size = 0.1,
                              group.by = "time")

dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_NK_only_Dgat2.pdf"))
dev.off()





# goi <- c("Nkg7", "Itga1", "Itga2", "Dgat1", "Dgat2")
# 
# scCustomize::Stacked_VlnPlot(kaede.seurat.NK, 
#                              features = goi,
#                              pt.size = 0,
#                              group.by = "time")
# 
# dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_grouped_by_colour_dgat.pdf"))
# dev.off()
# 
# 
# Idents(kaede.seurat) <- kaede.seurat@meta.data$celltype_cluster_paper
# temp.seurat <- subset(kaede.seurat, idents = c("NK_1", "NK_2", "NK_5"))
# scCustomize::Stacked_VlnPlot(temp.seurat, 
#                              features = goi,
#                              pt.size = 0.1,
#                              group.by = "celltype_cluster_paper")
# 
# dev.copy(pdf, paste0(output.dir, "Vlnplot_kaede_select_NK_groups_dgat.pdf"))
# dev.off()





```





